# Generated by Django 3.2.25 on 2024-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeblog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
